name: calculadora_neps

description: Calculadora VICUNHA de Neps dividido para 0.09 m con exportacion PDF, CSV, Excel e impresion.

publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  shared_preferences_windows: ^2.4.1
  pdf: 3.11.1
  printing: 5.13.4
  excel: 4.0.6
  path_provider: ^2.1.5
  path_provider_windows: ^2.3.0
  share_plus: ^11.0.0
  file_picker: ^10.3.10
  provider: ^6.1.2
  firebase_core: ^4.10.0
  firebase_core_web: ^3.4.0
  cloud_firestore: ^6.5.0
  cloud_firestore_web: ^5.2.0
  firebase_auth: ^6.5.2
  firebase_auth_web: ^6.2.0
  cloud_functions: ^6.0.6
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.0.0
  fl_chart: ^0.70.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
